### ISSUE TITLE
Integrate iter8-trend into Kiali

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/kiali#20]
Was working. Broken now. Needs to work for iter8 v1.0.0.

**Comment by jadeyliu939** [comment]
After install Istio 1.6, Iter8-Trend is not showing data in Kiali.
The Query returns results are
```
iter8_trend{app="unknown",baseline="reviews-v2",instance="iter8-trend.iter8:8888",job="iter8_trend",metric="iter8_mean_latency",name="reviews-v3-rollout",namespace="bookinfo-iter8",phase="Completed",service_name="reviews",start_time="2020-10-23T20:19:53Z",time="2020-10-23T20:21:58Z",version="unknown",winner="reviews-v3"}
```

Where the app="unknown" could be the problem.

After consult with Joel Takvorian from Redhat, here is his response

>
Yes, app unknown looks like a problem. You have no idea why it is like this? I don't know the details of how this metric is created; basically, this label comes either from the producer of the metric, or from prometheus itself depending on its configuration (e.g. via label mapping config). Kiali expects that the app label in prometheus matches the app label of the kubernetes pods. In this example it should be "reviews" I guess.

>
Actually, there was a problem in some versions of istio including 1.6 , but I'm not sure if it's the cause here. See https://github.com/istio/istio/issues/24075
The default configuration of Prometheus prevented some pod metrics to be read. But I don't know if iter8 relies on that.
>
If this is the problem, then you would have to edit the prometheus configuration or reinstall istio with a special flag "meshConfig.enablePrometheusMerge=true".
This flag was turned on by default in istio 1.7 so the problem disappeared.


But after upgrade to Istio 1.7, iter8-trend is still not showing correct data.

**Comment by jadeyliu939** [comment]
Problem Identifies:

1. App and Version are showing unknown
2. Namespace has been changed to kubernetes_namespace in the latest Istio installation.

==== From Joel =====
in the latest Istio they changed "namespace" to "kubernetes_namespace".
So we changed that as well in Kiali (and we made it configurable, now we can tell Kiali which label to expect for namespaces).
See how this is now is Kiali config, we don't have anymore the "custom_prometheus_url" setting, it's replaced with a richer section of "custom_dashboards":

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L407-L427

For instance you can have:
```
    custom_dashboards:
      enabled: true
      namespace_label: "kubernetes_namespace"
      prometheus:
        url: "http://bahblah"
```

**Comment by jadeyliu939** [comment]
Split the iter8_trend query into 5 sub-query ( iter8_trend_cpu, iter8_trend_mem, iter8_trend_disk, iter8_trend_network and iter_trend_cutom). and build 5 charts as the following

![Screen Shot 2020-11-01 at 10.23.20 AM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/2ed3a4a8-6cf8-4b4d-8134-31486e00d563)

**Comment by jadeyliu939** [comment]
Dropdown selections
![Screen Shot 2020-11-01 at 10.29.21 AM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/a687583d-9377-471f-b5db-292b1db0de80)

**Comment by jadeyliu939** [comment]
Iter8 monitoringdashboard YAML

```
apiVersion: monitoring.kiali.io/v1alpha1
kind: MonitoringDashboard
name: iter8
namespace: istio-system
spec:
  discoverOn: iter8_trend
  items:
  - chart:
      aggregations:
      - displayName: Disk Read/Write
        label: diskmetric
      chartType: bar
      dataType: raw
      groupLabels:
      - version
      metrics:
      - displayName: Disk Read/Write
        metricName: iter8_trend_disk
      name: Disk Read/Write
      sortLabel: time
      sortLabelParseAs: int
      spans: 6
      xAxis: series
  - chart:
      aggregations:
      - displayName: Network Send/Receive
        label: networkmetric
      chartType: bar
      dataType: raw
      groupLabels:
      - version
      metrics:
      - displayName: Network Send/Receive
        metricName: iter8_trend_network
      name: Network Send/Receive
      sortLabel: time
      sortLabelParseAs: int
      spans: 6
      xAxis: series
  - chart:
      aggregations:
      - displayName: Iter8 Experiment Metrics
        label: iter8metric
        singleSelection: true
      chartType: bar
      dataType: raw
      groupLabels:
      - version
      metrics:
      - displayName: Iter8 Experiment Metrics
        metricName: iter8_trend_custom
      name: Iter8 Experiment Metrics
      sortLabel: time
      sortLabelParseAs: int
      spans: 6
      xAxis: series
  - chart:
      chartType: bar
      dataType: raw
      groupLabels:
      - version
      metrics:
      - displayName: CPU
        metricName: iter8_trend_cpu
      name: CPU
      sortLabel: time
      sortLabelParseAs: int
      spans: 3
      xAxis: series
  - chart:
      chartType: bar
      dataType: raw
      groupLabels:
      - version
      metrics:
      - displayName: Memory
        metricName: iter8_trend_mem
      name: Memory
      sortLabel: time
      sortLabelParseAs: int
      spans: 3
      xAxis: series
  title: Iter8 Metrics
```
