### ISSUE TITLE
Enable Kiali with iter8 extension in our cluster

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/kiali#21]

**Comment by jadeyliu939** [comment]
Iter8 enable for kiali in openshift cluster

Use `open https://$(oc get routes -n istio-system kiali -o jsonpath='{.spec.host}')/console` to access kiali

**Comment by kalantar** [comment]
Looks good!

**Comment by jadeyliu939** [comment]
How the Kiali is enabled for Iter8

1. Update the kiali cr `oc edit kialis.kiali.io kiali -n istio-system`

2. Add the following to the spec

```
spec:
   deployment:
      image_name: quay.io/kiali/kiali
      image_pull_policy: Always
   extensions:
       iter_8:
         enabled: true
```

3. Make sure the Kiali pod is restarted 

Note: the Kiali operator can be found in openshift-operators namespace
      image_version: v1.25.0
