### ISSUE TITLE
Iter8 Experiment creation templates

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali#26]
Iter8 Experiment Templates are installed in the configmap, for example
`kubectl  create configmap iter8-experiment-templates --from-file=simple=canary-simple.yaml --from-file=traffic=canary-traffic.yaml -n iter8`

the default configmap name is `iter8-experiment-templates`, and can be changed by specified in the Kiali Iter8 Extension configuration 
```
type Iter8Config struct {
	Enabled bool `yaml:"enabled"`
	// Define which namespace Iter8 is installed on, default to iter8
	Namespace string `yaml:"namespace"`
	TemplateConfigMap string `yaml:"template_configmap"`
}
```

Example of Template
```
# Simple Experiment
# Using Iter8 Mean Latency
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: {{.experiment_name}}
spec:
  service:
    name: {{.service_name}}
    baseline: {{.baseline}}
    candidates: {{range .candidates}}
      - {{.}}
    {{- end}}
  criteria:
    - metric: iter8_mean_latency
      threshold:
        type: absolute
        value: 200
  duration:
    maxIterations: 8
    interval: 15s
  trafficControl:
    maxIncrement: 20
```
