### ISSUE TITLE
Validate Iter8 installation

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali#4]
Validate Iter8 Installation and versioning control

**Comment by jadeyliu939** [comment]
Meeting (04-07) 
1. Use Iter8 Analytics API to do health check and query for algorithm
2. Use Pod Health and version # to health check on Iter8 Controller

**Comment by jadeyliu939** [comment]
Assume using configmap for Iter8 Controller that specified the analytics service URI, which is then used by Kiali backend to check the health of Iter8 Analytics services.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config
  namespace: iter8
data:
  analyticsServices: |-
    - name: incluter1
      version: v1
      uri: https://something
    - name: external1
      version: v1
      uri: https://somethingelse.com
```
